name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        default: 'latest'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: prod
    steps:
      - name: login 👀 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{secrets.DEPLOYPATH}}
            bash deploy.sh ${{ github.event.inputs.name }}
